<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['comite_LifeStyle'] = array(
	'table'=>'comite_lifestyle',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'marital_status' => 
  array (
    'required' => false,
    'name' => 'marital_status',
    'vname' => 'LBL_MARITAL_STATUS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'single',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'marital_status_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'have_children' => 
  array (
    'required' => false,
    'name' => 'have_children',
    'vname' => 'LBL_HAVE_CHILDREN',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'have_children_notes' => 
  array (
    'required' => false,
    'name' => 'have_children_notes',
    'vname' => 'LBL_HAVE_CHILDREN_NOTES',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'have_grandchildren' => 
  array (
    'required' => false,
    'name' => 'have_grandchildren',
    'vname' => 'LBL_HAVE_GRANDCHILDREN',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'have_grandchildren_notes' => 
  array (
    'required' => false,
    'name' => 'have_grandchildren_notes',
    'vname' => 'LBL_HAVE_GRANDCHILDREN_NOTES',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'occupation' => 
  array (
    'required' => false,
    'name' => 'occupation',
    'vname' => 'LBL_OCCUPATION',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'hobbies' => 
  array (
    'required' => false,
    'name' => 'hobbies',
    'vname' => 'LBL_HOBBIES',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'family_ties' => 
  array (
    'required' => false,
    'name' => 'family_ties',
    'vname' => 'LBL_FAMILY_TIES',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'travel_international' => 
  array (
    'required' => false,
    'name' => 'travel_international',
    'vname' => 'LBL_TRAVEL_INTERNATIONAL',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'travel_international_notes' => 
  array (
    'required' => false,
    'name' => 'travel_international_notes',
    'vname' => 'LBL_TRAVEL_INTERNATIONAL_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'seatbelt_user' => 
  array (
    'required' => false,
    'name' => 'seatbelt_user',
    'vname' => 'LBL_SEATBELT_USER',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'always',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'seatbelt_use_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'have_smoke_detector' => 
  array (
    'required' => false,
    'name' => 'have_smoke_detector',
    'vname' => 'LBL_HAVE_SMOKE_DETECTOR',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'have_carbon_monoxide_detector' => 
  array (
    'required' => false,
    'name' => 'have_carbon_monoxide_detector',
    'vname' => 'LBL_HAVE_CARBON_MONOXIDE_DETECTOR',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'tobacco_use_current' => 
  array (
    'required' => true,
    'name' => 'tobacco_use_current',
    'vname' => 'LBL_TOBACCO_USE_CURRENT',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'tobacco_use_current_length' => 
  array (
    'required' => false,
    'name' => 'tobacco_use_current_length',
    'vname' => 'LBL_TOBACCO_USE_CURRENT_LENGTH',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tobacco_use_attempted_quit' => 
  array (
    'required' => false,
    'name' => 'tobacco_use_attempted_quit',
    'vname' => 'LBL_TOBACCO_USE_ATTEMPTED_QUIT',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'tobacco_use_past' => 
  array (
    'required' => true,
    'name' => 'tobacco_use_past',
    'vname' => 'LBL_TOBACCO_USE_PAST',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'tobacco_use_past_length' => 
  array (
    'required' => false,
    'name' => 'tobacco_use_past_length',
    'vname' => 'LBL_TOBACCO_USE_PAST_LENGTH',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tobacco_use_past_quit' => 
  array (
    'required' => false,
    'name' => 'tobacco_use_past_quit',
    'vname' => 'LBL_TOBACCO_USE_PAST_QUIT',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'alcohol_avg_weekly_consumption' => 
  array (
    'required' => true,
    'name' => 'alcohol_avg_weekly_consumption',
    'vname' => 'LBL_ALCOHOL_AVG_WEEKLY_CONSUMPTION',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'alcohol_weekly_consumption_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'stress_under_great_deal' => 
  array (
    'required' => true,
    'name' => 'stress_under_great_deal',
    'vname' => 'LBL_STRESS_UNDER_GREAT_DEAL',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'stress_under_great_deal_notes' => 
  array (
    'required' => false,
    'name' => 'stress_under_great_deal_notes',
    'vname' => 'LBL_STRESS_UNDER_GREAT_DEAL_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'stress_relief_methods' => 
  array (
    'required' => false,
    'name' => 'stress_relief_methods',
    'vname' => 'LBL_STRESS_RELIEF_METHODS',
    'type' => 'multienum',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'options' => 'stress_relief_methods_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'stress_relief_methods_other' => 
  array (
    'required' => false,
    'name' => 'stress_relief_methods_other',
    'vname' => 'LBL_STRESS_RELIEF_METHODS_OTHER',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'sleep_average_per_night' => 
  array (
    'required' => false,
    'name' => 'sleep_average_per_night',
    'vname' => 'LBL_SLEEP_AVERAGE_PER_NIGHT',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'sleep_need_per_night' => 
  array (
    'required' => false,
    'name' => 'sleep_need_per_night',
    'vname' => 'LBL_SLEEP_NEED_PER_NIGHT',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'sleep_wake_fully_rested' => 
  array (
    'required' => false,
    'name' => 'sleep_wake_fully_rested',
    'vname' => 'LBL_SLEEP_WAKE_FULLY_RESTED',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'sleep_pattern_changes' => 
  array (
    'required' => true,
    'name' => 'sleep_pattern_changes',
    'vname' => 'LBL_SLEEP_PATTERN_CHANGES',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'sleep_morning_difficult_out' => 
  array (
    'required' => true,
    'name' => 'sleep_morning_difficult_out',
    'vname' => 'LBL_SLEEP_MORNING_DIFFICULT_OUT',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('comite_LifeStyle','comite_LifeStyle', array('basic','assignable'));