<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$vardefs = array (
  'fields' => 
  array (
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '255',
      'unified_search' => false,
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'selected',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'size' => '20',
    ),
    'test_date' => 
    array (
      'required' => false,
      'name' => 'test_date',
      'vname' => 'LBL_TEST_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'size' => '20',
      'enable_range_search' => false,
    ),
    'bds_lumbar_spine' => 
    array (
      'required' => false,
      'name' => 'bds_lumbar_spine',
      'vname' => 'LBL_BDS_LUMBAR_SPINE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_femoral_neck_left' => 
    array (
      'required' => false,
      'name' => 'bds_femoral_neck_left',
      'vname' => 'LBL_BDS_FEMORAL_NECK_LEFT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_femoral_neck_right' => 
    array (
      'required' => false,
      'name' => 'bds_femoral_neck_right',
      'vname' => 'LBL_BDS_FEMORAL_NECK_RIGHT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_total_hip_left' => 
    array (
      'required' => false,
      'name' => 'bds_total_hip_left',
      'vname' => 'LBL_BDS_TOTAL_HIP_LEFT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_total_hip_right' => 
    array (
      'required' => false,
      'name' => 'bds_total_hip_right',
      'vname' => 'LBL_BDS_TOTAL_HIP_RIGHT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_forearm_left' => 
    array (
      'required' => false,
      'name' => 'bds_forearm_left',
      'vname' => 'LBL_BDS_FOREARM_LEFT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_forearm_right' => 
    array (
      'required' => false,
      'name' => 'bds_forearm_right',
      'vname' => 'LBL_BDS_FOREARM_RIGHT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_region_of_forearm_left' => 
    array (
      'required' => false,
      'name' => 'bds_region_of_forearm_left',
      'vname' => 'LBL_BDS_REGION_OF_FOREARM_LEFT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'bds_region_of_forearm_right' => 
    array (
      'required' => false,
      'name' => 'bds_region_of_forearm_right',
      'vname' => 'LBL_BDS_REGION_OF_FOREARM_RIGHT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'normal',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'bone_density_scan_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'vda_normal' => 
    array (
      'required' => false,
      'name' => 'vda_normal',
      'vname' => 'LBL_VDA_NORMAL',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'vda_mild_wedge_deformity' => 
    array (
      'required' => false,
      'name' => 'vda_mild_wedge_deformity',
      'vname' => 'LBL_VDA_MILD_WEDGE_DEFORMITY',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'vda_mild_wedge_deformity_note' => 
    array (
      'required' => false,
      'name' => 'vda_mild_wedge_deformity_note',
      'vname' => 'LBL_VDA_MILD_WEDGE_DEFORMITY_NOTE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'vda_moderate_wedge_deformity' => 
    array (
      'required' => false,
      'name' => 'vda_moderate_wedge_deformity',
      'vname' => 'LBL_VDA_MODERATE_WEDGE_DEFORMITY',
      'type' => 'bool',
      'massupdate' => 0,
      'default' => '0',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'vda_moderate_wedge_deformity_note' => 
    array (
      'required' => false,
      'name' => 'vda_moderate_wedge_deformity_note',
      'vname' => 'LBL_VDA_MODERATE_WEDGE_DEFORMITY_NOTE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_left_arm_lean_muscle' => 
    array (
      'required' => false,
      'name' => 'bc_left_arm_lean_muscle',
      'vname' => 'LBL_BC_LEFT_ARM_LEAN_MUSCLE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_left_arm_fat_mass' => 
    array (
      'required' => false,
      'name' => 'bc_left_arm_fat_mass',
      'vname' => 'LBL_BC_LEFT_ARM_FAT_MASS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_left_arm_fat_percent' => 
    array (
      'required' => false,
      'name' => 'bc_left_arm_fat_percent',
      'vname' => 'LBL_BC_LEFT_ARM_FAT_PERCENT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_right_arm_lean_muscle' => 
    array (
      'required' => false,
      'name' => 'bc_right_arm_lean_muscle',
      'vname' => 'LBL_BC_RIGHT_ARM_LEAN_MUSCLE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_right_arm_fat_mass' => 
    array (
      'required' => false,
      'name' => 'bc_right_arm_fat_mass',
      'vname' => 'LBL_BC_RIGHT_ARM_FAT_MASS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_right_arm_fat_percent' => 
    array (
      'required' => false,
      'name' => 'bc_right_arm_fat_percent',
      'vname' => 'LBL_BC_RIGHT_ARM_FAT_PERCENT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_trunk_lean_muscle' => 
    array (
      'required' => false,
      'name' => 'bc_trunk_lean_muscle',
      'vname' => 'LBL_BC_TRUNK_LEAN_MUSCLE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_trunk_fat_mass' => 
    array (
      'required' => false,
      'name' => 'bc_trunk_fat_mass',
      'vname' => 'LBL_BC_TRUNK_FAT_MASS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_trunk_fat_percent' => 
    array (
      'required' => false,
      'name' => 'bc_trunk_fat_percent',
      'vname' => 'LBL_BC_TRUNK_FAT_PERCENT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_left_leg_lean_muscle' => 
    array (
      'required' => false,
      'name' => 'bc_left_leg_lean_muscle',
      'vname' => 'LBL_BC_LEFT_LEG_LEAN_MUSCLE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_left_leg_fat_mass' => 
    array (
      'required' => false,
      'name' => 'bc_left_leg_fat_mass',
      'vname' => 'LBL_BC_LEFT_LEG_FAT_MASS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_left_leg_fat_percent' => 
    array (
      'required' => false,
      'name' => 'bc_left_leg_fat_percent',
      'vname' => 'LBL_BC_LEFT_LEG_FAT_PERCENT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_right_leg_lean_muscle' => 
    array (
      'required' => false,
      'name' => 'bc_right_leg_lean_muscle',
      'vname' => 'LBL_BC_RIGHT_LEG_LEAN_MUSCLE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_right_leg_fat_mass' => 
    array (
      'required' => false,
      'name' => 'bc_right_leg_fat_mass',
      'vname' => 'LBL_BC_RIGHT_LEG_FAT_MASS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_right_leg_fat_percent' => 
    array (
      'required' => false,
      'name' => 'bc_right_leg_fat_percent',
      'vname' => 'LBL_BC_RIGHT_LEG_FAT_PERCENT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_subtotal_lean_muscle' => 
    array (
      'required' => false,
      'name' => 'bc_subtotal_lean_muscle',
      'vname' => 'LBL_BC_SUBTOTAL_LEAN_MUSCLE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_subtotal_fat_mass' => 
    array (
      'required' => false,
      'name' => 'bc_subtotal_fat_mass',
      'vname' => 'LBL_BC_SUBTOTAL_FAT_MASS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'bc_subtotal_fat_percent' => 
    array (
      'required' => false,
      'name' => 'bc_subtotal_fat_percent',
      'vname' => 'LBL_BC_SUBTOTAL_FAT_PERCENT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => '6',
      'cols' => '80',
      'required' => false,
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'size' => '20',
      'studio' => 'visible',
    ),
  ),
  'relationships' => 
  array (
  ),
);