<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$vardefs = array (
  'fields' => 
  array (
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'date',
      'link' => true,
      'dbType' => 'varchar',
      'len' => '255',
      'unified_search' => false,
      'required' => true,
      'importable' => 'required',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'selected',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'size' => '20',
    ),
    'fit_assess_general_exercise' => 
    array (
      'required' => false,
      'name' => 'fit_assess_general_exercise',
      'vname' => 'LBL_FIT_ASSESS_GENERAL_EXERCISE',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => 'yes',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'yes_no_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'fit_assess_general_exercise_re' => 
    array (
      'required' => false,
      'name' => 'fit_assess_general_exercise_re',
      'vname' => 'LBL_FIT_ASSESS_GENERAL_EXERCISE_RE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_height' => 
    array (
      'required' => false,
      'name' => 'fit_assess_height',
      'vname' => 'LBL_FIT_ASSESS_HEIGHT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_weight' => 
    array (
      'required' => false,
      'name' => 'fit_assess_weight',
      'vname' => 'LBL_FIT_ASSESS_WEIGHT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_waist' => 
    array (
      'required' => false,
      'name' => 'fit_assess_waist',
      'vname' => 'LBL_FIT_ASSESS_WAIST',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_heartrate' => 
    array (
      'required' => false,
      'name' => 'fit_assess_heartrate',
      'vname' => 'LBL_FIT_ASSESS_HEARTRATE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_bloodpressure' => 
    array (
      'required' => false,
      'name' => 'fit_assess_bloodpressure',
      'vname' => 'LBL_FIT_ASSESS_BLOODPRESSURE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_respiration' => 
    array (
      'required' => false,
      'name' => 'fit_assess_respiration',
      'vname' => 'LBL_FIT_ASSESS_RESPIRATION',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_pushup' => 
    array (
      'required' => false,
      'name' => 'fit_assess_pushup',
      'vname' => 'LBL_FIT_ASSESS_PUSHUP',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_abcrunch' => 
    array (
      'required' => false,
      'name' => 'fit_assess_abcrunch',
      'vname' => 'LBL_FIT_ASSESS_ABCRUNCH',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_plank' => 
    array (
      'required' => false,
      'name' => 'fit_assess_plank',
      'vname' => 'LBL_FIT_ASSESS_PLANK',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_grip' => 
    array (
      'required' => false,
      'name' => 'fit_assess_grip',
      'vname' => 'LBL_FIT_ASSESS_GRIP',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_grip_l' => 
    array (
      'required' => false,
      'name' => 'fit_assess_grip_l',
      'vname' => 'LBL_FIT_ASSESS_GRIP_L',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_balance' => 
    array (
      'required' => false,
      'name' => 'fit_assess_balance',
      'vname' => 'LBL_FIT_ASSESS_BALANCE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_balance_l' => 
    array (
      'required' => false,
      'name' => 'fit_assess_balance_l',
      'vname' => 'LBL_FIT_ASSESS_BALANCE_L',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => '255',
      'size' => '20',
    ),
    'fit_assess_posture' => 
    array (
      'required' => false,
      'name' => 'fit_assess_posture',
      'vname' => 'LBL_FIT_ASSESS_POSTURE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_posture_a',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_posture_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_hamstring' => 
    array (
      'required' => false,
      'name' => 'fit_assess_hamstring',
      'vname' => 'LBL_FIT_ASSESS_HAMSTRING',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_hamstring_good',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_hamstring_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_lumbar' => 
    array (
      'required' => false,
      'name' => 'fit_assess_lumbar',
      'vname' => 'LBL_FIT_ASSESS_LUMBAR',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_lumbar_good',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_lumbar_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_thotacic' => 
    array (
      'required' => false,
      'name' => 'fit_assess_thotacic',
      'vname' => 'LBL_FIT_ASSESS_THOTACIC',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_thotacic_list',
      'studio' => 'visible',
      'dependency' => false,
      'default' => 'fit_assess_thotacic_good',
    ),
    'fit_assess_cervical' => 
    array (
      'required' => false,
      'name' => 'fit_assess_cervical',
      'vname' => 'LBL_FIT_ASSESS_CERVICAL',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_cervical_good',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_cervical_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_shoulder_p' => 
    array (
      'required' => false,
      'name' => 'fit_assess_shoulder_p',
      'vname' => 'LBL_FIT_ASSESS_SHOULDER_P',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_shoulder_p_good',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_shoulder_p_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_shoulder_f' => 
    array (
      'required' => false,
      'name' => 'fit_assess_shoulder_f',
      'vname' => 'LBL_FIT_ASSESS_SHOULDER_F',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_shoulder_f_good',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_shoulder_f_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_soleus' => 
    array (
      'required' => false,
      'name' => 'fit_assess_soleus',
      'vname' => 'LBL_FIT_ASSESS_SOLEUS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_soleus_good',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_soleus_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_posture_assess' => 
    array (
      'required' => false,
      'name' => 'fit_assess_posture_assess',
      'vname' => 'LBL_FIT_ASSESS_POSTURE_ASSESS',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
    ),
    'fit_assess_toepoint' => 
    array (
      'required' => false,
      'name' => 'fit_assess_toepoint',
      'vname' => 'LBL_FIT_ASSESS_TOEPOINT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_toepoint_outward',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_toepoint_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_knees' => 
    array (
      'required' => false,
      'name' => 'fit_assess_knees',
      'vname' => 'LBL_FIT_ASSESS_KNEES',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_knees_outward',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_knees_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_medial' => 
    array (
      'required' => false,
      'name' => 'fit_assess_medial',
      'vname' => 'LBL_FIT_ASSESS_MEDIAL',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_medial_flat',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_medial_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_elbow' => 
    array (
      'required' => false,
      'name' => 'fit_assess_elbow',
      'vname' => 'LBL_FIT_ASSESS_ELBOW',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_elbow_extended',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_elbow_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_shoulder' => 
    array (
      'required' => false,
      'name' => 'fit_assess_shoulder',
      'vname' => 'LBL_FIT_ASSESS_SHOULDER',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_shoulder_flexion',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_shoulder_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_lumbar_squat' => 
    array (
      'required' => false,
      'name' => 'fit_assess_lumbar_squat',
      'vname' => 'LBL_FIT_ASSESS_LUMBAR_SQUAT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_lumbar_squat_lordosis',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_shoulder_0',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_pelvic' => 
    array (
      'required' => false,
      'name' => 'fit_assess_pelvic',
      'vname' => 'LBL_FIT_ASSESS_PELVIC',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_pelvic_left',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_pelvic_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_scapular' => 
    array (
      'required' => false,
      'name' => 'fit_assess_scapular',
      'vname' => 'LBL_FIT_ASSESS_SCAPULAR',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => 'fit_assess_scapular_protraction',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'fit_assess_scapular_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'fit_assess_squat_assessment' => 
    array (
      'required' => false,
      'name' => 'fit_assess_squat_assessment',
      'vname' => 'LBL_FIT_ASSESS_SQUAT_ASSESSMENT',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
    ),
  ),
  'relationships' => 
  array (
  ),
);