<?PHP
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN comite_PersonalHealthHistory
 */


class comite_PersonalHealthHistory_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'comite_PersonalHealthHistory';
	var $object_name = 'comite_PersonalHealthHistory';
	var $table_name = 'comite_personalhealthhistory';
	var $importable = false;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $last_doctor_visit;
		var $doctor_visits_within_year;
		var $dental_health;
		var $sick_days;
		var $hospital_days;
		var $hosptial_days_explanation;
		var $surgical_procedures;
		var $trauma_history;
		var $blood_transfusion;
		var $blood_transfusion_explanation;
		var $radiation_therapy;
		var $radiation_therapy_reason;
		var $chemotherapy;
		var $chemotherapy_explanation;
		var $gender;
		var $height;
		var $weight;
		var $weight_highest;
		var $weight_lowest;
		var $weight_ideal;
		var $blood_type;
		var $patient_rate_current_health;
		var $age_management_medical_goals;
		var $body_frame;
		var $pri_physician_name;
		var $pri_physician_address1;
		var $pri_physician_address2;
		var $pri_physician_city;
		var $pri_physician_state;
		var $pri_physician_zip;
		var $pri_physician_phone_office;
		var $pri_physician_fax;
		var $pri_physician_email_office;
		var $diagnostic_proc_additiona;
		var $exposure_additional;
		var $is_no_current_supplements;
		var $is_no_current_medications;
		var $men_med_enhancementdrugs_use;
		var $men_med_enhancementdrugs_notes;
		var $men_med_enhancementdrugs_has_h;
		var $men_med_sexual_function_use;
		var $men_med_sexual_function_notes;
		var $men_med_sexual_function_helped;
		var $men_med_testosterone_use;
		var $men_med_testosterone_notes;
		var $men_med_testosterone_helped;
		var $fem_med_enhancementdrugs_use;
		var $fem_med_enhancementdrugs_notes;
		var $fem_med_enhancementdrugs_help;
		var $fem_med_birthcontrol_use;
		var $fem_med_birthcontrol_notes;
		function comite_PersonalHealthHistory_sugar(){	
		parent::Basic();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>