<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['comite_PersonalHealthHistory'] = array(
	'table'=>'comite_personalhealthhistory',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'last_doctor_visit' => 
  array (
    'required' => false,
    'name' => 'last_doctor_visit',
    'vname' => 'LBL_LAST_DOCTOR_VISIT',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Year',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  'doctor_visits_within_year' => 
  array (
    'required' => false,
    'name' => 'doctor_visits_within_year',
    'vname' => 'LBL_DOCTOR_VISITS_WITHIN_YEAR',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  'dental_health' => 
  array (
    'required' => false,
    'name' => 'dental_health',
    'vname' => 'LBL_DENTAL_HEALTH',
    'type' => 'multienum',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'options' => 'dental_health_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'sick_days' => 
  array (
    'required' => false,
    'name' => 'sick_days',
    'vname' => 'LBL_SICK_DAYS',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  'hospital_days' => 
  array (
    'required' => false,
    'name' => 'hospital_days',
    'vname' => 'LBL_HOSPITAL_DAYS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'hospital_days_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'hosptial_days_explanation' => 
  array (
    'required' => false,
    'name' => 'hosptial_days_explanation',
    'vname' => 'LBL_HOSPTIAL_DAYS_EXPLANATION',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'surgical_procedures' => 
  array (
    'required' => false,
    'name' => 'surgical_procedures',
    'vname' => 'LBL_SURGICAL_PROCEDURES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'trauma_history' => 
  array (
    'required' => false,
    'name' => 'trauma_history',
    'vname' => 'LBL_TRAUMA_HISTORY',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'blood_transfusion' => 
  array (
    'required' => true,
    'name' => 'blood_transfusion',
    'vname' => 'LBL_BLOOD_TRANSFUSION',
    'type' => 'radioenum',
    'massupdate' => 0,
    'default' => 'no',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dbType' => 'enum',
    'separator' => '<br>',
  ),
  'blood_transfusion_explanation' => 
  array (
    'required' => false,
    'name' => 'blood_transfusion_explanation',
    'vname' => 'LBL_BLOOD_TRANSFUSION_EXPLANATION',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'radiation_therapy' => 
  array (
    'required' => false,
    'name' => 'radiation_therapy',
    'vname' => 'LBL_RADIATION_THERAPY',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'radiation_therapy_reason' => 
  array (
    'required' => false,
    'name' => 'radiation_therapy_reason',
    'vname' => 'LBL_RADIATION_THERAPY_REASON',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'chemotherapy' => 
  array (
    'required' => false,
    'name' => 'chemotherapy',
    'vname' => 'LBL_CHEMOTHERAPY',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'chemotherapy_explanation' => 
  array (
    'required' => false,
    'name' => 'chemotherapy_explanation',
    'vname' => 'LBL_CHEMOTHERAPY_EXPLANATION',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'gender' => 
  array (
    'required' => false,
    'name' => 'gender',
    'vname' => 'LBL_GENDER',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '__',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'gender_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'height' => 
  array (
    'required' => false,
    'name' => 'height',
    'vname' => 'LBL_HEIGHT',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '8',
  ),
  'weight' => 
  array (
    'required' => false,
    'name' => 'weight',
    'vname' => 'LBL_WEIGHT',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '8',
  ),
  'weight_highest' => 
  array (
    'required' => false,
    'name' => 'weight_highest',
    'vname' => 'LBL_WEIGHT_HIGHEST',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '8',
  ),
  'weight_lowest' => 
  array (
    'required' => false,
    'name' => 'weight_lowest',
    'vname' => 'LBL_WEIGHT_LOWEST',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '8',
  ),
  'weight_ideal' => 
  array (
    'required' => false,
    'name' => 'weight_ideal',
    'vname' => 'LBL_WEIGHT_IDEAL',
    'type' => 'decimal',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '8',
  ),
  'blood_type' => 
  array (
    'required' => false,
    'name' => 'blood_type',
    'vname' => 'LBL_BLOOD_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'dont_know',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'blood_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'patient_rate_current_health' => 
  array (
    'required' => false,
    'name' => 'patient_rate_current_health',
    'vname' => 'LBL_PATIENT_RATE_CURRENT_HEALTH',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'fair',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'patient_rate_current_health_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'age_management_medical_goals' => 
  array (
    'required' => false,
    'name' => 'age_management_medical_goals',
    'vname' => 'LBL_AGE_MANAGEMENT_MEDICAL_GOALS',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'body_frame' => 
  array (
    'required' => false,
    'name' => 'body_frame',
    'vname' => 'LBL_BODY_FRAME',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'medium',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'body_frame_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pri_physician_name' => 
  array (
    'required' => false,
    'name' => 'pri_physician_name',
    'vname' => 'LBL_PRI_PHYSICIAN_NAME',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'pri_physician_address1' => 
  array (
    'required' => false,
    'name' => 'pri_physician_address1',
    'vname' => 'LBL_PRI_PHYSICIAN_ADDRESS1',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'pri_physician_address2' => 
  array (
    'required' => false,
    'name' => 'pri_physician_address2',
    'vname' => 'LBL_PRI_PHYSICIAN_ADDRESS2',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'pri_physician_city' => 
  array (
    'required' => false,
    'name' => 'pri_physician_city',
    'vname' => 'LBL_PRI_PHYSICIAN_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'pri_physician_state' => 
  array (
    'required' => false,
    'name' => 'pri_physician_state',
    'vname' => 'LBL_PRI_PHYSICIAN_STATE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'AL',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'state_dom',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'pri_physician_zip' => 
  array (
    'required' => false,
    'name' => 'pri_physician_zip',
    'vname' => 'LBL_PRI_PHYSICIAN_ZIP',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'pri_physician_phone_office' => 
  array (
    'required' => false,
    'name' => 'pri_physician_phone_office',
    'vname' => 'LBL_PRI_PHYSICIAN_PHONE_OFFICE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'pri_physician_fax' => 
  array (
    'required' => false,
    'name' => 'pri_physician_fax',
    'vname' => 'LBL_PRI_PHYSICIAN_FAX',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'pri_physician_email_office' => 
  array (
    'required' => false,
    'name' => 'pri_physician_email_office',
    'vname' => 'LBL_PRI_PHYSICIAN_EMAIL_OFFICE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'diagnostic_proc_additiona' => 
  array (
    'required' => false,
    'name' => 'diagnostic_proc_additiona',
    'vname' => 'LBL_DIAGNOSTIC_PROC_ADDITIONA',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'exposure_additional' => 
  array (
    'required' => false,
    'name' => 'exposure_additional',
    'vname' => 'LBL_EXPOSURE_ADITIONAL',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'is_no_current_supplements' => 
  array (
    'required' => false,
    'name' => 'is_no_current_supplements',
    'vname' => 'LBL_IS_NO_CURRENT_SUPPLEMENTS',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'is_no_current_medications' => 
  array (
    'required' => false,
    'name' => 'is_no_current_medications',
    'vname' => 'LBL_IS_NO_CURRENT_MEDICATIONS',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'men_med_enhancementdrugs_use' => 
  array (
    'required' => false,
    'name' => 'men_med_enhancementdrugs_use',
    'vname' => 'LBL_MEN_MED_ENHANCEMENTDRUGS_USE',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'men_med_enhancementdrugs_notes' => 
  array (
    'required' => false,
    'name' => 'men_med_enhancementdrugs_notes',
    'vname' => 'LBL_MEN_MED_ENHANCEMENTDRUGS_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'men_med_enhancementdrugs_has_h' => 
  array (
    'required' => false,
    'name' => 'men_med_enhancementdrugs_has_h',
    'vname' => 'LBL_MEN_MED_ENHANCEMENTDRUGS_HAS_H',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'men_med_sexual_function_use' => 
  array (
    'required' => false,
    'name' => 'men_med_sexual_function_use',
    'vname' => 'LBL_MEN_MED_SEXUAL_FUNCTION_USE',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'men_med_sexual_function_notes' => 
  array (
    'required' => false,
    'name' => 'men_med_sexual_function_notes',
    'vname' => 'LBL_MEN_MED_SEXUAL_FUNCTION_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'men_med_sexual_function_helped' => 
  array (
    'required' => false,
    'name' => 'men_med_sexual_function_helped',
    'vname' => 'LBL_MEN_MED_SEXUAL_FUNCTION_HELPED',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'men_med_testosterone_use' => 
  array (
    'required' => false,
    'name' => 'men_med_testosterone_use',
    'vname' => 'LBL_MEN_MED_TESTOSTERONE_USE',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'men_med_testosterone_notes' => 
  array (
    'required' => false,
    'name' => 'men_med_testosterone_notes',
    'vname' => 'LBL_MEN_MED_TESTOSTERONE_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'men_med_testosterone_helped' => 
  array (
    'required' => false,
    'name' => 'men_med_testosterone_helped',
    'vname' => 'LBL_MEN_MED_TESTOSTERONE_HELPED',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'fem_med_enhancementdrugs_use' => 
  array (
    'required' => false,
    'name' => 'fem_med_enhancementdrugs_use',
    'vname' => 'LBL_FEM_MED_ENHANCEMENTDRUGS_USE',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'fem_med_enhancementdrugs_notes' => 
  array (
    'required' => false,
    'name' => 'fem_med_enhancementdrugs_notes',
    'vname' => 'LBL_FEM_MED_ENHANCEMENTDRUGS_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'fem_med_enhancementdrugs_help' => 
  array (
    'required' => false,
    'name' => 'fem_med_enhancementdrugs_help',
    'vname' => 'LBL_FEM_MED_ENHANCEMENTDRUGS_HELP',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'fem_med_birthcontrol_use' => 
  array (
    'required' => false,
    'name' => 'fem_med_birthcontrol_use',
    'vname' => 'LBL_FEM_MED_BIRTHCONTROL_USE',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'type' => 'enum',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
  ),
  'fem_med_birthcontrol_notes' => 
  array (
    'required' => false,
    'name' => 'fem_med_birthcontrol_notes',
    'vname' => 'LBL_FEM_MED_BIRTHCONTROL_NOTES',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'description' => 
  array (
    'name' => 'description',
    'vname' => 'LBL_DESCRIPTION',
    'type' => 'text',
    'comment' => 'Full text of the note',
    'rows' => '6',
    'cols' => '80',
    'required' => false,
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'studio' => 'visible',
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('comite_PersonalHealthHistory','comite_PersonalHealthHistory', array('basic','assignable'));